#数据报表类

class Entirety(object):
    def __init__(self, data):
        self.id = data["id"]
        self.name = data["name"]
        self.num = data["num"]
        self.pmax = data["pmax"]
        self.p1 = data["p1"]
        self.e = data["e"]
        self.k21 = data["k21"]
        self.k01 = data["k01"]
        self.k22 = data["k22"]
        self.k02 = data["k02"]
        self.k23 = data["k23"]
        self.k03 = data["k03"]
        self.k24 = data["k24"]
        self.k04 = data["k04"]
        self.p4 = data["p4"]
        self.p5 = data["p5"]
        self.k1 = data["k1"]
        self.k31 = data["k31"]
        self.pn1 = data["pn1"]
        self.k32 = data["k32"]
        self.pn2 = data["pn2"]
        self.k33 = data["k33"]
        self.pn3 = data["pn3"]
        self.k34 = data["k34"]
        self.pn4 = data["pn4"]
        self.bRun = data["bRun"]
        self.bStartBack = data["bStartBack"]
        self.bWaterWork = data["bWaterWork"]
        self.bStop = data["bStop"]


